In [16]:
import sqlite3
import pandas as pd
from db_setup import setup_database
setup_database()
conn=sqlite3.connect('bookcycle.db')
query = """SELECT * FROM books LIMIT 5;"""
results_df = pd.read_sql(query, conn)
display(results_df)

,book_id,title,author,isbn,genre,condition,purchase_price,list_price,date_acquired,current_location,quantity
0,B1001,A Christmas Carol,Charles Dickens,9780141324524,Classic Fiction,Good,5.5,8.99,2023-01-15,Suburban,2
1,B1002,A Farewell to Arms,Ernest Hemingway,9780684801469,Classic Fiction,Very Good,7.0,11.99,2023-01-15,University,3
2,B1003,A Tale of Two Cities,Charles Dickens,9780141439600,Classic Fiction,Fair,4.5,7.99,2023-01-16,Downtown,2
3,B1004,Adventures of Huckleberry Finn,Mark Twain,9780142437179,Classic Fiction,Good,6.0,9.99,2023-01-16,University,4
4,B1005,Agnes Grey,Anne Bronte,9780140432107,Classic Fiction,Fair,4.0,7.99,2023-01-17,Suburban,1

In [8]:
query2="SELECT * FROM books;"
results_df2=pd.read_sql(query2,conn)
display(results_df2)

,book_id,title,author,isbn,genre,condition,purchase_price,list_price,date_acquired,current_location,quantity
0,B1001,A Christmas Carol,Charles Dickens,9780141324524,Classic Fiction,Good,5.5,8.99,2023-01-15,Suburban,2
1,B1002,A Farewell to Arms,Ernest Hemingway,9780684801469,Classic Fiction,Very Good,7.0,11.99,2023-01-15,University,3
2,B1003,A Tale of Two Cities,Charles Dickens,9780141439600,Classic Fiction,Fair,4.5,7.99,2023-01-16,Downtown,2
3,B1004,Adventures of Huckleberry Finn,Mark Twain,9780142437179,Classic Fiction,Good,6.0,9.99,2023-01-16,University,4
4,B1005,Agnes Grey,Anne Bronte,9780140432107,Classic Fiction,Fair,4.0,7.99,2023-01-17,Suburban,1
...,...,...,...,...,...,...,...,...,...,...,...
95,B1096,Thus Spoke Zarathustra,Friedrich Nietzsche,9780140441185,Classic Philosophy,Like New,8.0,13.99,2023-03-03,University,3
96,B1097,Treasure Island,Robert Louis Stevenson,9780141321011,Classic Fiction,Fair,4.5,7.99,2023-03-04,Suburban,2
97,B1098,Ulysses,James Joyce,9780141182803,Classic Fiction,Very Good,8.0,13.99,2023-03-04,University,3
98,B1099,Walden,Henry David Thoreau,9780140390445,Classic Non-Fiction,Good,6.5,10.99,2023-03-05,University,4
99,B1100,Wuthering Heights,Emily Bronte,9780141439556,Classic Fiction,Like New,7.5,12.99,2023-03-05,University,4

In [12]:
query3="SELECT title FROM books WHERE author='Oscar Wilde';"
result_df3=pd.read_sql(query3,conn)
display(result_df3)

                             title
0  The Importance of Being Earnest
1       The Picture of Dorian Gray

In [13]:
query4="SELECT title, list_price FROM books WHERE list_price<10;"
results_df4=pd.read_sql(query4,conn)
display(results_df4)

                                          title  list_price
0                             A Christmas Carol        8.99
1                          A Tale of Two Cities        7.99
2                Adventures of Huckleberry Finn        9.99
3                                    Agnes Grey        7.99
4                                        Anthem        8.99
5                                       Beowulf        9.99
6                                   Bleak House        8.99
7                                       Candide        8.99
8                              Canterbury Tales        7.99
9                             David Copperfield        9.99
10                                      Dracula        7.99
11                           Great Expectations        9.99
12                           Gulliver's Travels        8.99
13                            Heart of Darkness        9.99
14                                In Cold Blood        9.99
15                                Julius Caesar        7.99
16                                      Macbeth        9.99
17                                Madame Bovary        8.99
18                                        Medea        9.99
19                                  Middlemarch        9.99
20                                        Night        9.99
21                       Notes from Underground        7.99
22                                 Oliver Twist        9.99
23                                      Othello        9.99
24                                Paradise Lost        8.99
25                              Robinson Crusoe        7.99
26                        Sense and Sensibility        9.99
27                              Sons and Lovers        9.99
28                    Tess of the d'Urbervilles        8.99
29                         The Age of Innocence        9.99
30                         The Call of the Wild        9.99
31                         The Canterbury Tales        8.99
32              The Importance of Being Earnest        9.99
33                                   The Jungle        8.99
34                                   The Prince        8.99
35  The Strange Case of Dr. Jekyll and Mr. Hyde        9.99
36                            The Tale of Genji        9.99
37                               The Waste Land        9.99
38                      The Wind in the Willows        9.99
39                              Treasure Island        7.99

In [ ]:
query5="SELECT customer_id, join_date, is_member FROM Customer; "
result_df5=pd.read_sql(query5,conn)
display(result_df5)

    is_member
0           1
1           0
2           1
3           1
4           0
..        ...
95          1
96          0
97          1
98          1
99          0

[100 rows x 1 columns]

In [20]:
query6="SELECT customer_id, preferred_store FROM Customers WHERE preferred_store='Downtown';"
result_df6=pd.read_sql(query6,conn)
display(result_df6)

   customer_id preferred_store
0        C1003        Downtown
1        C1007        Downtown
2        C1010        Downtown
3        C1014        Downtown
4        C1018        Downtown
5        C1022        Downtown
6        C1025        Downtown
7        C1029        Downtown
8        C1032        Downtown
9        C1036        Downtown
10       C1040        Downtown
11       C1043        Downtown
12       C1047        Downtown
13       C1050        Downtown
14       C1053        Downtown
15       C1056        Downtown
16       C1059        Downtown
17       C1062        Downtown
18       C1065        Downtown
19       C1068        Downtown
20       C1071        Downtown
21       C1074        Downtown
22       C1077        Downtown
23       C1080        Downtown
24       C1083        Downtown
25       C1086        Downtown
26       C1089        Downtown
27       C1092        Downtown
28       C1095        Downtown
29       C1098        Downtown